# This workflow will translate the README.md file to all languages available in the Crowdin project.
# https://github.com/marketplace/actions/translate-readme
name: Translate Readme

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  translate-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Translate Readme
        uses: crowdin/translate-readme@v0.1.0
        with:
          language_switcher: true
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: New Readme Translations by Crowdin
          body: By [translate-readme](https://github.com/crowdin/translate-readme) GitHub action
          commit-message: New Readme Translations
          committer: Crowdin Bot <support+bot@crowdin.com>
          branch: docs/readme-translations
